### ISSUE TITLE
대명사처리가 요약된 문장에 있는 그 단어에 대해서만 Coreference Resolution화 합니다.

### ISSUE THREAD

**Issue by KMUKKS** [kookmin-sw/2019-cap1-2019_17#1]
<img width="1440" alt="스크린샷 2019-05-09 오후 7 35 50" src="https://user-images.githubusercontent.com/21335827/57447438-0a977300-7292-11e9-8f5b-3df806bf2ad5.png">

그림에서 보이는 거와 같이 대명사처리가 전체 본문내용에 적용되지 않고 요약된 문장으로만 coreference Resolution하는 현상입니다.

어떻게 전체 본문 내용에 대해 요약된 문장과 함께  @coreference resolution을 적용시킬수 있을까요?
@msmf3

**Comment by msmf3** [comment]
coreference resolution 을 전처리 과정에 포함해 본문내용에 적용되도록 바꿨습니다.

**Comment by msmf3** [comment]
![image](https://user-images.githubusercontent.com/43058677/57749801-90943d80-771a-11e9-98b2-d02dbb80fcdd.png)
CoreferenceResolution 클래스를 추가하였고
![image](https://user-images.githubusercontent.com/43058677/57749842-b4578380-771a-11e9-8ee7-86ae91308446.png)
TextRank 클래스에서 이를 이용하게끔 하였습니다.
